apiVersion: v2
name: infra
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: strimzi-kafka-operator
    version: "0.45.x"
    repository: "https://strimzi.io/charts/"
