apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name }}-kb
spec:
  version: {{ .Values.elkVersion | default "8.12.0" }}
  count: 1
  elasticsearchRef:
    name: {{ .Release.Name }}-es
  http:
    service:
      spec:
        type: {{ .Values.kibana.serviceType | default "NodePort" }}
        ports:
          - name: https
            port: 5601
            targetPort: 5601
            {{- if and (eq .Values.kibana.serviceType "NodePort") .Values.kibana.nodePort }}
            nodePort: {{ .Values.kibana.nodePort }}
            {{- end }}
