apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
type: Opaque
stringData:
  objstore.yml: |
    type: FILESYSTEM
    config:
      directory: /prometheus/thanos-local-storage # 저장 경로
