apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-monitor
  namespace: infra
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  namespaceSelector:
    matchNames:
      - infra
  endpoints:
    - port: metrics
      interval: 30s
