apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ .Release.Namespace }} # 'log' 네임스페이스에 생성
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-role-binding
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: filebeat-role
  apiGroup: rbac.authorization.k8s.io
