apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 4.1.0
    # replicas와 storage는 KafkaNodePool에서 관리하므로 정의하지 않습니다.
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      # Replica가 1대일 때 필수적인 안전 설정
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {} # 토픽 생성을 자동화해주는 오퍼레이터
    userOperator: {}  # 사용자 권한을 관리해주는 오퍼레이터
