# kafka-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack # Helm 설치 시 사용한 이름과 일치해야 함
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  namespaceSelector:
    matchNames:
      - kafka # Exporter가 살고 있는 네임스페이스
  endpoints:
    - port: metrics
      interval: 30s # 30초마다 수집
