apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: k8s-logs
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000 # 1시간 (테스트용이므로 짧게 설정)
    segment.bytes: 1073741824
