apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Release.Name }}-kb
spec:
  version: {{ .Values.elkVersion | default "8.12.0" }}
  count: 1
  elasticsearchRef:
    # 위에서 정의한 Elasticsearch의 이름과 연결
    name: {{ .Release.Name }}-es
