# nginx-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      run: test-nginx # kubectl run으로 만들었을 때 기본 레이블
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s
