# nginx-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack # 프로메테우스가 찾고 있는 레이블과 일치
spec:
  selector:
    matchLabels:
      app: test-nginx # 서비스(Service)에 설정된 app: test-nginx 레이블과 일치시켜야 함
  namespaceSelector:
    matchNames:
      - default # 서비스가 떠 있는 네임스페이스
  endpoints:
    - port: metrics # 서비스 포트 이름(9113)
      interval: 15s
      path: /metrics
