# 1. Nginx 설정 (Stub Status 활성화)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-status-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        # 익스포터가 내부적으로 데이터를 읽어갈 수 있도록 설정
        location /stub_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    }
---
# 2. Nginx & Exporter 사이드카 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: status-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: exporter
          image: nginx/nginx-prometheus-exporter:latest
          args:
            - -nginx.scrape-uri=http://localhost:80/stub_status
          ports:
            - containerPort: 9113
      volumes:
        - name: status-conf
          configMap:
            name: nginx-status-config
---
# 3. 서비스 (두 개의 포트 노출)
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: default
  labels:
    app: test-nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
  selector:
    app: test-nginx
